name       : simgear
version    : 2018.3.2
release    : 7
source     :
    - https://netix.dl.sourceforge.net/project/flightgear/release-2018.3/simgear-2018.3.2.tar.bz2 : c8b094a8c5045362848781f72117dbec424472bf6b9dd135dfe43f9b915781a4
license    : GPL-2.0-or-later
component  : programming.library
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - libboost-devel
setup      : |
    %cmake_ninja \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DSYSTEM_EXPAT=ON \
build      : |
    %ninja_build
install    : |
    %ninja_install
