name       : simgear
version    : 2018.2.2
release    : 5
source     :
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2018.2/simgear-2018.2.2.tar.bz2 : f61576bc36aae36f350154749df1cee396763604c06b8a71c4b50452d9151ce5
license    : GPL-2.0-or-later
component  : programming
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - libboost-devel
setup      : |
    mkdir sgbuild && pushd sgbuild
    %cmake -DSIMGEAR_SHARED=ON \
           -DSYSTEM_EXPAT=ON \
           -DCMAKE_INSTALL_LIBDIR=%libdir% \
           ..
    popd
build      : |
    pushd sgbuild
    %make
    popd
install    : |
    pushd sgbuild
    %make_install
    popd
check      : |
    pushd sgbuild
    # test_dns requires networking
    #%make test
    popd
