name       : simgear
version    : 2018.3.6
release    : 13
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2018.3/simgear-2018.3.6.tar.bz2 : 1939cd4e2820e1b182833ec2ef0c4757bcdc949a1a8b8c20c930f47876416f7a
license    : GPL-2.0-or-later
component  : programming.library
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/simgear-2019.1.1-gdal3.patch

    %cmake_ninja \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DENABLE_SIMD=ON \
        -DSYSTEM_EXPAT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
