name       : simgear
version    : 2018.3.1
release    : 6
source     :
    - https://netix.dl.sourceforge.net/project/flightgear/release-2018.3/simgear-2018.3.1.tar.bz2 : 294580c8e98044f660d2a9d202856970a4ce9d81ff0107fffcbd701d36daa06a
license    : GPL-2.0-or-later
component  : programming.library
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - libboost-devel
setup      : |
    %cmake_ninja \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DSYSTEM_EXPAT=ON \
build      : |
    %ninja_build
install    : |
    %ninja_install
