name       : simgear
version    : 2020.3.6
release    : 17
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2020.3/simgear-2020.3.6.tar.bz2 : ec3eca44d21f7e052beafc1b9e2d57c16fbc1ad5f033abc967b57afd02c35669
license    : GPL-2.0-or-later
component  : programming.library
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/simgear-2019.1.1-gdal3.patch

    %cmake_ninja \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DENABLE_SIMD=ON \
        -DSYSTEM_EXPAT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
