name       : simgear
version    : 2016.3.1
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/flightgear/release-2016.3/simgear-2016.3.1.tar.bz2 : ae46e1273673be41028ee912d1826e87185ab594053c493707f9dbdeea5159dd
license    : GPL-2.0
component  : programming
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - libboost-devel
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DSIMGEAR_SHARED=1 \
           -DSYSTEM_EXPAT=1 \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
