name       : simgear
version    : 2020.3.18
release    : 26
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2020.3/simgear-2020.3.18.tar.bz2/download : 6cc1cf2556b172407929ecf2bab2432c6fb05ee16dd19026e90369f2573636ca
homepage   : https://www.flightgear.org/
license    : GPL-2.0-or-later
component  : programming.library
summary    : A set of open-source libraries for 3D simulations and games
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/simgear-2019.1.1-gdal3.patch

    %cmake_ninja \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DENABLE_SIMD=ON \
        -DSYSTEM_EXPAT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
