name       : simgear
version    : 2017.1.3
release    : 3
source     :
    - https://github.com/FlightGear/simgear/archive/version/2017.1.3.tar.gz : b145821420478a234afaddd83e974b1e2c96b48ae8acd033dd1527d50fcf2d20
license    : GPL-2.0
component  : programming
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(gl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - libboost-devel
setup      : |
    mkdir build
    cd build
    %cmake -DSIMGEAR_SHARED=1 \
           -DSYSTEM_EXPAT=1 \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
