name       : simgear
version    : 2018.3.5
release    : 12
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2018.3/simgear-2018.3.5.tar.bz2 : b409a2bf46b25bfc8a453a7ff71a58baee597ae5a557d9e0980588908da978ee
license    : GPL-2.0-or-later
component  : programming.library
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/simgear-2019.1.1-gdal3.patch

    %cmake_ninja \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DENABLE_SIMD=ON \
        -DSYSTEM_EXPAT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
