name       : simgear
version    : 2017.3.1
release    : 4
source     :
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2017.3/simgear-2017.3.1.tar.bz2 : 0ee08550b737b249dcc91590ec0cb9c5dc9080998f6ba66a7d7209cdfce6e1f4
license    : GPL-2.0
component  : programming
summary    : SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations
description: |
    SimGear is a set of open-source libraries designed to be used as building blocks for quickly assembling 3d simulations, games, and visualization applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - libboost-devel
setup      : |
    mkdir sgbuild && pushd sgbuild
    %cmake -DSIMGEAR_SHARED=ON \
           -DSYSTEM_EXPAT=ON \
           -DCMAKE_INSTALL_LIBDIR=%libdir% \
           ..
    popd
build      : |
    pushd sgbuild
    %make
    popd
install    : |
    pushd sgbuild
    %make_install
    popd
check      : |
    pushd sgbuild
    # test_dns requires networking
    #%make test
    popd
